const motivationalQuotes: string[] = [
    "Believe you can and you're halfway there.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to do great work is to love what you do.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream bigger. Do bigger.",
    "Don’t limit your challenges. Challenge your limits.",
    "Work hard in silence. Let success make the noise.",
    "Doubt kills more dreams than failure ever will.",
    "Your limitation—it’s only your imagination.",
    "Stay positive, work hard, make it happen.",
    "Push through the pain, you’re stronger than you think.",
    "You are capable of amazing things.",
    "Start where you are. Use what you have. Do what you can.",
    "Discipline is the bridge between goals and accomplishment.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Failure is not the opposite of success, it’s part of success.",
    "Success usually comes to those who are too busy to be looking for it."
  ];
  
  export default motivationalQuotes;